<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>{{ config('app.name', 'Laravel') }}</title>
        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
        <!-- Fonts -->
        {{-- <link rel="dns-prefetch" href="//fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Poppins" rel="stylesheet">
         --}}
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
        <!-- Styles -->
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
        <link href="{{ asset('css/styles.css') }}" rel="stylesheet">
        <meta name="google-site-verification" content="XbMSSqM0fiA3vpNaSWY98ygdwyZTFa7NymBow21wPWQ" />
    </head>
    <body class="welcomeBody">
        <div class="container welcomeCont">
            <div class="row justify-content-center">
                <a class="navbar-brand logoimg" href="{{ url('/') }}"><img src="{{ asset('images/logo.png') }}" alt="Uptick Logo" title="Uptick Logo" /></a>
                <h1>Privacy Policy</h1>
                <p>This Privacy Policy (the “Privacy Policy”) governs the manner in which Uptick LLC (“Uptick”) collects, uses, maintains, and discloses information collected from users (each, a “User”) of its <a href="https://uptick.co.il/" target="_blank">www.uptick.co.il</a> website, applications, and technology platform, and any derivative or affiliated websites on which this Privacy Policy is posted, linked, or referenced (collectively, the “Site”). The Site is owned and operated by Uptick. Please note that this Privacy Policy covers Uptick' practices regarding information collected from its Site. Please read this Privacy Policy carefully to understand how we handle your information. By using the Site, you agree to the terms of this Privacy Policy. You shouldn't use the Site if you don't agree with this Privacy Policy or any other agreement that governs your use of the Site.</p>
                <h2>The Information Uptick Collects and Receives</h2>
                <p>The categories of information that are collected will depend upon the nature of your interaction(s) with Uptick and the Site. Below are examples to help you better understand the data we collect.</p>
                <p>We collect contact information. When you submit an inquiry through the Site, we collect your name, email address, and phone number if provided, along with general information about the nature of your inquiry. When you create an account through the Site, we will also collect your username, password, mailing address, and other information related to providing you services through the Site.</p>
                <p>We collect payment information from customers. If you make a purchase with us, we (or our business partner(s) who process payment transactions for us) may collect your billing or other financial information in order to process the transaction(s). Please note that for security we do not store sensitive cardholder data, such as full credit or debit card numbers or card authentication data.</p>
                <p>We collect professional and education-related information from tutors, instructors, experts, and educators. Tutors, instructors, experts, and educators (“Professionals”) who seek to enter into independent contractor agreements with Uptick or its related and/or affiliated entities are asked to provide additional personal information in support of the Professional’s respective skills and experience, as well as a social security number or taxpayer identification number for tax purposes, as necessary to facilitate payment and to comply with legal obligations. Professionals also have choices about the information the Professional chooses to include on the Professional’s profile on the Site once under contract, such as education, work experience, skills, city or area, likes or interests, photo, etc.</p>
                <p>We collect payment information for Professionals. If you are a contracted Professional through the Site, then we (or our business partner(s) who process payment transactions for us) will collect bank account or other financial information in order to facilitate payments to you based upon invoices you submit through the Site and in conjunction with your signed independent contractor agreement(s). Please note that for security we do not collect or store sensitive bank account information.</p>
                <p>We collect information you submit or otherwise provide or authorize us to collect. We collect the information you post on our Site. This includes comments, reviews, documents, questions, chats, messages, assessments, videos, or photos. Such shared content may be publicly viewable by others depending on where it is posted, shared, or viewed. We also collect any other information you may provide to us or authorize us to collect, including any other identifier that permits the ability to contact you. If you communicate with Uptick by e-mail; post messages to forums; make telephone or cell phone calls or texts; communicate through electronic devices or other interactive devices; complete online forms, surveys, sweepstakes, or contest entries; or communicate with Uptick by any means, any information provided in such communication may be collected by Uptick.</p>
                <p>We collect demographic information and information about your interests. We may collect information such as your zip code, gender, age, income, household or lifestyle information, and information about your interests and preferences.</p>
                <p>We collect information about third parties that you provide to us. A User may also provide personally identifiable information about others, such as emergency contact information for notification in the event a situation requires it. If you choose to use our referral service to refer a friend to our Site, then you may provide your referral’s name and email address, as further detailed in the Refer-A-Friend section below. If you submit any personal information about another individual to us, then you are responsible for making sure that you have the authority to do so and to allow us to use their personal information in accordance with this Privacy Policy.</p>
                <p>We collect information through surveys, testimonials, comments, reviews, and blogs. You may decide to participate in a survey, to provide a review, to provide a testimonial, to comment on a blog or social media post, etc. If you decide to participate or comment, then you may provide certain information that may include personal information. In addition, we may post customer testimonials/comments/reviews on our Site that may contain personally identifiable information; however, if/when that happens, we obtain the person's consent via email or other means prior to posting the testimonial, which authorizes us to post certain information along with their testimonial. We may invite you to complete a survey or participate in a promotion, either through the Site or through a third-party platform. If you participate, we will collect and store the data you provide as part of participating. That data is subject to this Privacy Policy unless otherwise stated in the official rules of the promotion or survey, including notifying winners and distributing rewards. Where we use a third-party platform to administer a survey or promotion, the third party’s privacy policy will apply.</p>
                <p>We collect internet and electronic network activity information, such as device and usage information. We may collect information about your browser type, language preference, referring site, subsequent site, and date/time of each visitor request. The purpose in collecting non-personally identifying information is to better understand how Users use the Site. We may collect information about your operating system, Internet Service provider information and IP addresses and other device identifiers, such as mobile device information. In addition, we may collect information about your use of the Site, unique views, originating sites, etc., including through the use of tracking technologies (See section pertaining to Tracking Technologies for more information). A User browsing the Site without registering an account or affirmatively providing personally identifiable information to Uptick does so anonymously.</p>
                <p>We collect analytics information. We use certain third-party services to assist us in analysis, auditing, research, and reporting regarding the Site. These third parties may use web logs or web beacons, and they may set and access cookies on your computer or other device. In particular, we use Google Analytics to help collect and analyze certain information for the purposes discussed in this Policy. You may opt out of the use of cookies by Google Analytics at <a href="https://tools.google.com/dlpage/gaoptout" target="_blank">https://tools.google.com/dlpage/gaoptout</a>.</p>
                <h2>How Uptick Uses Information</h2>
                <p>Uptick may use personally identifiable information collected through the Site for the following reasons:</p>
                <ul>
                    <li>for the specific purposes for which the information was collected;</li>
                    <li>to fulfill a contractual obligation;</li>
                    <li>to contact Users regarding Uptick' live-learning platform;</li>
                    <li>to communicate to Users regarding products and services offered through Uptick, its parent, subsidiaries, and trusted affiliates;</li>
                    <li>to maintain and improve its products, services, and sites;</li>
                    <li>to provide support;</li>
                    <li>to enhance Users’ experiences with Uptick;</li>
                    <li>to inform Users of offerings that may be of interest;</li>
                    <li>to process payments;</li>
                    <li>for business planning, marketing, advertising and sales purposes;</li>
                    <li>for information security purposes;</li>
                    <li>to defend its legal rights;</li>
                    <li>to efficiently maintain its business; and</li>
                    <li>to comply with applicable law.</li>
                </ul>
                <h2>Information Sharing</h2>
                <p>We may share information that we collect about you in the following ways:</p>
                <p>We share information with our service providers and third-party vendors. We contract with select third party vendors to provide services on our behalf, for example, services such as email, hosting, cloud storage, maintenance, backup and analysis, communications software, marketing, business strategy, banking, payment processing, professional services, background checks, etc. We also share non-personal information (such as aggregate user statistics, de-identified information, demographic information, etc.) with third parties such as advertisers, content providers, and analytics providers.</p>
                <p>We share information within the Uptick family of companies and brands. Uptick may disclose personally identifiable information collected from Users to its parent, subsidiaries and other related companies, trusted affiliates, independent contractors and business partners who will use the information for the purposes outlined in this Privacy Policy, as necessary to provide the services offered by or through Uptick and to provide the Site itself, and for the specific purposes for which the information was collected. These companies are not permitted to use your personally identifiable information in any other way. We may also share information with third parties with which we have a commercial relationship, such as an affiliate marketing agreement.</p>
                <p>We may share information with a Professional related to a student. In conducting the matching process between a student and a Professional, we may share a student’s information with the Professional who may provide or will be providing tutoring or instruction to the student so that the Professional may evaluate the engagement and personalize and tailor the tutoring/instruction to the student. In each case, we collect such information only insofar as is necessary or appropriate to fulfill the purpose of the User’s interaction with Uptick.</p>
                <p>We will share information to the extent that we are required to do so by law or to protect the company or others. Uptick may disclose personally identifiable information at the request of law enforcement or governmental agencies or in response to subpoenas, court orders, or other legal process, to establish, protect, or exercise Uptick’ legal or other rights or to defend against a legal claim or as otherwise required or allowed by law. Uptick may disclose personally identifiable information in order to protect the rights, property, or safety of a User or any other person. Uptick may disclose personally identifiable information to investigate or prevent a violation by User of any contractual or other relationship with Uptick or the perpetration of any illegal or harmful activity.</p>
                <p>We may share information in connection with any business acquisition, sale, or merger, or in connection with investor relations. Uptick may disclose or transfer personally identifiable information collected from Users in connection with or in contemplation of a sale of its assets or business or a merger, consolidation, or other reorganization of its business. Uptick may also disclose aggregate, anonymous data based on information collected from Users to investors and potential partners.</p>
                <p>Users may always refuse to supply personally-identifying information, with the caveat that it may prevent them from engaging in certain Site-related activities.</p>
                <h2>Cookies and Tracking Technologies</h2>
                <p>Uptick and our analytics and marketing providers use technologies such as cookies, beacons, tags, and scripts (collectively “cookies”), to analyze trends, administer the Site, track Users’ movements around the Site, and to gather demographic information about our User base as a whole. We may receive reports based on the use of these technologies by these companies on an individual and aggregated basis.</p>
                <p>We use cookies for tracking page view/usage (log data), estimating audience size and usage patterns, services metadata, device information, location information, saving Users’ preferences and settings information, advertising new content that relate to your interests, keeping track of advertisements and search engine results, and for authentication. Each User can control the use of cookies at the individual browser level by adjusting your browser settings. If you choose to block all cookies (including essential cookies), you may still use our Site, but your ability to use some or all features or areas of our Site may be limited.</p>
                <p>As is true of most websites, we gather certain information automatically and store it in log files. This information may include Internet protocol (IP) addresses, browser type, internet service provider (ISP), referring/exit pages, operating system, date/time stamp, and/or clickstream data. We may combine this automatically collected log information with other information we collect about you. We do this to improve services we offer you and to improve marketing, analytics, or site functionality.</p>
                <p>We implement Google Analytics features that use Display Advertising information for Google Analytics Demographics and Interest Reporting. You can read more about the cookies used by Google Analytics advertising features, by going to the Google Analytics Privacy Policy page. You can opt-out of Google Analytics for Display Advertising, to prevent your data from being used by <a href="https://tools.google.com/dlpage/gaoptout" target="_blank">Google Analytics</a>, by going to the Google Analytics <a href="https://tools.google.com/dlpage/gaoptout" target="_blank">opt-out page</a>. You can opt out of Facebook Analytics by following the instructions in its <a href="https://www.facebook.com/about/privacy" target="_blank">Data Policy</a> and <a href="https://www.facebook.com/policies/cookies/" target="_blank">Cookies & Other Storage Technologies section</a>.</p>
                <p>We, along with third-party vendors (including Google), use first-party cookies (such as the Google Analytics cookies) and third-party cookies (such as the DoubleClick cookies) to report how your ad impressions, other uses of ad services, and interactions with these ad impressions and ad services are related to visits to our website.</p>
                <h2>LSOs</h2>
                <p>Third Parties, with whom we partner to provide certain features on our Site or to display advertising based upon your Web browsing activity, use LSOs such as HTML 5 to collect and store information. Various browsers may offer their own management tools for removing HTML5 LSOs.</p>
                <h2>Behavioral Targeting</h2>
                <p>We partner with a third party ad network to either display advertising on our Site or to manage our advertising on other sites. Our ad network partner uses cookies and Web beacons to collect non-personally identifiable information about your activities on this and other Web sites to provide you targeted advertising based upon your interests. You can manage your preferences for these advertising programs through the following links: <a href="https://www.facebook.com/about/ads" target="_blank">Facebook</a>, <a href="https://adssettings.google.com/anonymous?sig=ACi0TCjLSUupJXCn0E2lUA3gMsF9Xwcbt7q-WJh4O6YpHnEvByK6Hc6PCtqKw3s-PiV0q4ZuBQDwZmHxSFyu3Tw2K3NunIUtbw&hl=en" target="_blank">Google</a>. Please note this would not opt you out of being served advertising. You will continue to receive generic ads.</p>
                <h2>Your Choices Regarding Your Information</h2>
                <p>Updating your account information: If you have an account, you may be able to review the information you provided to us by logging into your account page and adjusting the settings under the “Account” tab.</p>
                <p>Email communications: If you receive an unwanted email from us, you can update your preferences by accessing the email preferences in your account settings page, or you can use the unsubscribe link found at the bottom of the email to opt out of future emails; however, please note that you will continue to receive transaction-related emails regarding products or services you have requested. You may also submit a request to us <a href="https://uptick.co.il/contact-us/" target="_blank">here</a>.</p>
                <p>Telephone/Text communications: If you receive an unwanted call or message from us, you can update or phone preferences by accessing your phone preferences in your account settings page, or you can send a Do Not Call request to us at the following email address: <a href="mailto:hello@uptick.co.il">hello@uptick.co.il</a></p>
                <p>Regarding text messages, you may opt out of SMS by replying “STOP” to the message received.</p>
                <p>Do Not Track and other similar signals: Some internet browsers incorporate a “Do Not Track” or other similar feature; however, given that there is not a uniform way for browsers to communicate this signal, the Site does not currently support these signals.</p>
                <p>Cookies and Internet-based Advertising: You may stop, restrict, or remove the placement of cookies on your device by adjusting your preferences as your browser or device permits. The online advertising industry also provides websites from which you may opt out of receiving targeted ads from data partners and other advertising partners. These may be accessed at sites such as <a href="https://optout.aboutads.info/?c=2&lang=EN" target="_blank">www.aboutads.info/choices</a>.</p>
                <p>Deletion or Other Request: To request deletion of your information or for another request regarding your information, please complete the form request <a href="https://privacyportal-cdn.onetrust.com/dsarwebform/ffef8acc-d836-4aba-9461-f5d802e9b675/02cdfd0f-53bd-4020-aeeb-afc84808961e.html" target="_blank">here</a>. We will respond to your request within a reasonable timeframe, or otherwise in accordance with applicable law. We will retain your information for as long as your account is active or as needed to provide you services. We will retain and use your information as necessary to comply with our legal obligations, resolve disputes, and enforce our agreements. In addition to filling out the above-referenced request form, requests can be emailed to <a href="mailto:hello@uptick.co.il">hello@uptick.co.il</a>. For state-specific information or related rights, please see the state-specific sections below.</p>
                <h2>Data Retention</h2>
                <p>We store the information collected as described in this Privacy Policy for as long as you are a User of the Site and/or as necessary to fulfill the purpose(s) for which the information was collected, to provide services through the Site, to resolve disputes, to pursue legitimate business purposes, to enforce our agreements, to establish legal defenses, to prevent fraud, and to comply with applicable laws.</p>
                <h2>Security of Information</h2>
                <p>Uptick discloses potentially personally-identifying and personally-identifying information only to those of its employees, contractors, and affiliated organizations that (i) need to know that information in order to process transactions on our behalf or to provide tutoring services, and (ii) that have agreed not to disclose it to others. We take all measures reasonably necessary to protect against the unauthorized access, use, alteration, or destruction of potentially personally-identifying and personally-identifying information.</p>
                <p>Information about each User that is maintained on Uptick’ systems is protected using industry standard security measures. We follow generally accepted standards to protect the personal information submitted to us, both during transmission and once it is received. If you have any questions about the security of your personal information, you can contact us at <a href="mailto:hello@uptick.co.il">hello@uptick.co.il</a>. However, no security measures are perfect or impenetrable, and Uptick cannot guarantee that the information submitted to, maintained on, or transmitted from its systems will be completely secure. Uptick is not responsible for the circumvention of any privacy settings or security measures relating to the Site by any User or third parties.</p>
                <p>Your security is a priority and we strive to provide a safe and secure environment for our customers; however, please note that we cannot guarantee that the information submitted to, maintained on, or transmitted from our systems will be completely secure. If you do not feel comfortable sending your financial/credit card over the Internet, contact us and we will be happy to fill your order over the phone.</p>
                <h2>Links to 3rd Party Sites</h2>
                <p>Please note that the Site may contain links to other Sites. These linked sites may not be operated or controlled by Uptick. Uptick is not responsible for the privacy practices of these or any other Sites, and you access these Sites entirely at your own risk. Uptick recommends that you review the privacy practices of any other Sites that you choose to visit.</p>
                <p>Uptick is based, in Israel and this Site is hosted in the united states. If User is from from the European Union or other regions of the world with laws governing data collection and use that may differ from U.S. law and User is visiting, accessing, or otherwise using the Site, please note that any personally identifiable information that User provides to Uptick will be transferred to the United States. Any such personally identifiable information provided will be processed and stored in the United States by Uptick or a service provider acting on its behalf. By providing personally identifiable information to Uptick, User hereby specifically and expressly consents to such transfer and processing and the uses and disclosures set forth herein.</p>
                <h2>Social Media Widgets</h2>
                <p>Our Site includes Social Media Features, such as the Facebook Like button and Widgets, such as the Share this button or interactive mini-programs that run on our Site. These Features may collect your IP address, which page you are visiting on our Site, and may set a cookie to enable the Feature to function properly. Social Media Features and Widgets are either hosted by a third party or hosted directly on our Site. Your interactions with these Features are governed by the privacy policy of the company providing it.</p>
                <h2>Blogs</h2>
                <p>Anytime you post on our blog please be aware that you are posting using a third-party application, and we have no access or control over this information. To request removal of your personal information from any blog, you can either log into the third-party application and remove your comment or you can contact the appropriate third party application. Your interaction with these features is governed by the privacy policy of the company providing it.</p>
                <h2>Professionals’ Profiles/Bios</h2>
                <p>If you are contracted as a Professional through the Site, then the profile you create on our Site will be publicly accessible unless otherwise indicated. You may change the privacy settings of your profile and make it non-public through your account portal, or as otherwise set forth in the terms of your independent contractor agreement.</p>
                <h2>Children’s Privacy</h2>
                <p>Uptick products are specifically designed to function without third party access to a child’s personal information. Our Site does not collect or retain any personal information from children except as needed to facilitate tutoring for that student, who may be a minor. Uptick is committed to complying fully with the Children’s Online Privacy Protection Act of 1998 (“COPPA”). This Site assures the privacy of collected information in accordance with Uptick' Privacy Policy.</p>
                <p>Uptick is committed to safeguarding the information each User entrusts to Uptick and believes that every User should know how it utilizes the information collected from each User. Other than free information and materials that do not require any registrations or identifying information, the Site is not directed at children under 13 years of age, and Uptick does not knowingly collect personally identifiable information from children under 13 years of age online. For purposes of using the Site as a platform to connect with tutors, Parents may supply information such as name or age of their children in order for Uptick to assist facilitate the connection between student and tutor. Uptick may store this information in a secure digital format. Parents or guardians of children under 13 years of age may review or have deleted any personal information previously provided by the child, parent, or guardian that is ultimately collected by Uptick, if any, to connect the child with a tutor. If you seek to review or delete such information, contact Uptick at the below phone number or email address indicating what you would like to have done and Uptick will contact you for purposes of taking the requested action, including but not limited to refusing to permit the information’s further collection or use.</p>
                <h2>Refer-A-Friend</h2>
                <p>If you choose to use our referral service to refer a friend about our Site, we will ask you for your friend’s name and email address. We will automatically send your friend a one-time email inviting the referral to visit the Site. Uptick stores this information for the sole purpose of sending this one-time email and tracking the success of our referral program.</p>
                <h2>Changes to this Policy</h2>
                <p>We may update this Privacy Policy to reflect changes to our information practices. If we make any material changes, then we may notify you by email (sent to the e-mail address specified in your account) or by means of a notice on this Site prior to the change becoming effective. Please review this Privacy Policy periodically. Your continued use of the Site after any such change(s) signifies your acceptance of any changes.</p>
                <h2>Contacting Uptick</h2>
                <p>If you have any questions or comments about this Privacy Policy, you may contact Uptick via any of the following methods:</p>
                <p>Mail: Uptick ATTN: Legal,  Derech Menachem Begin 88</p>
                <p>Phone: <a href="tel:972544916655">+972 54-491-6655</a></p>
                <p>Email: <a href="mailto:hello@uptick.co.il">hello@uptick.co.il</a></p>
                <p>Information request form: Complete the form <a href="https://uptick.co.il/contact-us/" target="_blank">here</a>.</p>
                <h2>Your Nevada Privacy Rights</h2>
                <p>Nevada Revised Statute Section 603A permits a User that resides in Nevada the right to submit a verified request that Uptick not sell such User’s covered information. Nevada law defines “sale” to mean the exchange of certain types of personal information for monetary consideration to a person for the person to license or sell the information to additional persons. We do not currently sell personal information as defined under Nevada Revised Statute Section 603A. However, if you are a Nevada resident, you may still submit a verified request by completing the request form <a href="https://uptick.co.il/contact-us/" target="_blank">here</a> to opt out of sales and we will record your instructions and incorporate them in the future if our policy changes. We will verify your request using information associated with your account, including email address, and may need to request additional information.</p>
                <h2>Your California Privacy Rights</h2>
                <p>Subject to certain limitations, the California Consumer Privacy Act (CCPA) provides California consumers the right to: request disclosure about what personal information we collect, use, disclose, and sell; request to delete their personal information; opt out of any “sale” of personal information; and not be discriminated against for exercising such rights.</p>
                <p>California consumers may make a request pursuant to their rights under the CCPA by completing the request form <a href="https://uptick.co.il/contact-us/" target="_blank">here</a>. You may also submit a request by emailing <a href="mailto:hello@uptick.co.il">hello@uptick.co.il</a>.</p>
                <p>We will verify your request using information provided in the request, as compared against information associated with your account, including verification of the email address that was listed in the request form. We may need to request additional information in order to verify your identity. Depending upon the type of request you make, we may require a signed declaration under penalty of perjury stating that you are the individual whose personal information is being requested. If you use an authorized agent to submit a request, we may require that the authorized agent provide proof of your written permission, and that you verify your identity directly with us.</p>
                <p>We are committed to ensuring this Privacy Policy is accessible to individuals with disabilities. If you wish to access this Privacy Policy in an alternative format, please contact us as described above.</p>
                <p>We have explained our privacy practices in full in the foregoing sections of this Privacy Policy. Below we have provided a list of the categories of personal information as set forth in the CCPA that have been collected, disclosed for business purposes, or “sold” for commercial purposes (as defined by the CCPA) during the preceding 12 months, as well as certain other information. Please see the other sections of the Privacy Policy above for additional information and context related to the sharing of information. We do not consider the ways we share your personal information to comprise the sale of your information. Within the past 12 months, we may have disclosed the following categories of information about consumers for a business purpose:</p>
                <div class="table-responsive mt-4">
                    <table class="table table-striped table-bordered" id="myDataTable">
                        <thead>
                            <tr>
                                <th scope="col">Category of Information</th>
                                <th scope="col">Explanation</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="align-middle">Identifiers, such as your name, street address, phone number, IP address, or email address</td>
                                <td class="align-middle">We use this information to respond to your questions, to communicate with you, for marketing purposes, to enable you to participate in our offerings, and for other business purposes.</td>
                            </tr>
                            <tr>
                                <td class="align-middle">Commercial information, such as purchase history</td>
                                <td class="align-middle">Records of purchases or other histories.</td>
                            </tr>
                            <tr>
                                <td class="align-middle">Internet and electronic network activity</td>
                                <td class="align-middle">We may use this information to improve our services, to better understand the visitors who come to our Site and what content is of interest to them.</td>
                            </tr>
                            <tr>
                                <td class="align-middle">Geographic location information</td>
                                <td class="align-middle">We may use this information to improve the quality, security, and relevance of our services and for other business purposes.</td>
                            </tr>
                            <tr>
                                <td class="align-middle">Other electronic information, such as information you post in a public space</td>
                                <td class="align-middle">We may use this information to provide the services, and for other business services.</td>
                            </tr>
                            <tr>
                                <td class="align-middle">Inferences drawn from the above</td>
                                <td class="align-middle">We use this information to personalize your experience with us, to understand other profile preferences, characteristics, trends, abilities, and aptitudes, and for other business purposes.</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>
